import type { Metadata } from "next";
import "./globals.css";
import ReduxWraper from "./WRAPER/ReduxWraper";
import { ThemeProvider } from "./THEME/theme-provider";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`antialiased`}
      >
        <ReduxWraper>
          <ThemeProvider>
            {children}
          </ThemeProvider>
        </ReduxWraper>
      </body>
    </html>
  );
}
